services:
  builder:
    build:
      context: ./
      args:
        - SQUID_VERSION=4.10
    image: squid-openssl-builder:latest
    container_name: squid-openssl-builder
    volumes:
      - ./dist:/dist
